version: 2
jobs:
  build:
    docker:
      - image: fedora:latest
    steps:
      - run:
          name: Tools Installation
          command: |
            yum update -y
            yum install -y git wget libnsl lsof
      - checkout
      - run:
          name: Git Submodules Updater
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Binary Installation
          command: |
            wget https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz
            tar -xvf PHP_Linux-x86_64.tar.gz
      - run:
          name: Directory Installation
          command: mkdir plugins
      - run:
          name: Clone & Checkout pthreads
          command: |
            git clone https://github.com/pmmp/pthreads.git
            cd pthreads
            git checkout c8cfacda84f21032d6014b53e72bf345ac901dac
      - run:
          name: Composer Installation
          command: bin/php7/bin/php tests/bin/composer.phar install
      - run:
          name: Create new Server Software PHAR
          command: bin/php7/bin/php tests/bin/build.php
      - store_artifacts:
          path: plugins/Aldous
          destination: Generator
